apiVersion: v1
kind: ReplicationController
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: clairelee7522/clouddevopscapstone
          ports:
            - containerPort: 80